version: '3'
services:
  api:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
        - ./api
    depends_on: 
        - db
    env_file:
      - ./.env
    entrypoint: ["pipenv", "run", "gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
  db:
    restart: always
    image: "postgres"
    container_name: "my_postgres"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
